---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-<BUILD_TAG>
  namespace: default
  labels:
    app: demo-<BUILD_TAG>
spec:
  selector:
    matchLabels:
      app: demo-<BUILD_TAG>
  replicas: 1
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demo-<BUILD_TAG>
    spec:
      containers:
        - image: scg130/demo:<BUILD_TAG>
          imagePullPolicy: IfNotPresent
          name: demo-<BUILD_TAG>
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          envFrom:
            - configMapRef:
                name: novel-config

---
apiVersion: v1
kind: Service
metadata:
  name: demo-<BUILD_TAG>-svc
  namespace: default
  labels:
    app: demo
spec:
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: demo
