---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <PROJECT>-<TAG>
  namespace: default
  labels:
    app: <PROJECT>-<TAG>
spec:
  selector:
    matchLabels:
      app: <PROJECT>-<TAG>
  replicas: 1
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: <PROJECT>-<TAG>
    spec:
      containers:
        - image: scg130/<PROJECT>:<TAG>
          imagePullPolicy: IfNotPresent
          name: <PROJECT>-<TAG>
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: VER
              value: "<VER>"
          envFrom:
            - configMapRef:
                name: novel-config

---
apiVersion: v1
kind: Service
metadata:
  name: <PROJECT>-<TAG>-svc
  namespace: default
  labels:
    app: <PROJECT>
spec:
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: <PROJECT>
